sudo: false

language: cpp

branches:
  except:
    - /^feature.*$/

cache:
  - apt

env:
- DISTRO=ubuntu-trusty
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "QHBCY7S3ZYOtu5zujyMnyHg74srAIfFSKJbrlBdETk2T6YStPug3Z5PuY7ahXfPyM/4w7og8KyvuGZL0YsJrNaJSpsbDETtwvKEorzLjfKyRwDV2SyTpnSLauGgZmjPZnkXzp8lQIR+cIo7of6frjxd47E8WCKCGFJKa0pUG5Bw="
  matrix:
    - BUILD=gcc
#    - BUILD=clang

#before_install:
#  - sudo pip install cpp-coveralls

before_script:
  - mkdir build
  - cd build

script:
  - ${CC} --version ; ${CXX} --version ; gcov --version
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
      case ${BUILD} in
        gcc)
          cmake ../ &&
          make &&
          make test
          ;;
        clang)
          cmake -DCMAKE_TOOLCHAIN_FILE=../src/linux/cmake/clang.cmake ../  &&
          make &&
          make test
          ;;
      esac ;
    fi

after_success:
  - coveralls --verbose --root .. --build-root . --exclude src/json/ --exclude src/tests/ --exclude src/linux/epoll/tests/ --exclude build/CMakeFiles/CompilerIdC/ --exclude build/CMakeFiles/CompilerIdCXX/ --gcov-options '\-lp'

addons:
  coverity_scan:
    project:
      name: "gatzka/cjet"
      description: "Build submitted via Travis CI"
    build_script_url: https://raw.githubusercontent.com/gatzka/cjet/coverity_scan/scripts/travis/travisci_build_coverity_scan.sh
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "cmake ../"
    build_command: "make"
    branch_pattern: coverity_scan

  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libboost-dev
    - libboost-test-dev   
    - gcc-5
    - g++-5

