language: cpp

env:
  matrix:
   - COMPILER=gcc
   - COMPILER=clang

install:
  - sudo apt-get install cmake

before_script:
  - mkdir build
  - cd build

script:
  - case ${COMPILER} in
      gcc)
        cmake ../linux/epoll/  &&
        make
        ;;
      clang)
        cmake -DCMAKE_TOOLCHAIN_FILE=../linux/clang.cmake ../linux/epoll/  &&
        make
        ;;
    esac ;

