language: cpp

env:
  matrix:
   - COMPILER=gcc
   - COMPILER=clang

install:
  - sudo apt-get install cmake

before_script:
  - mkdir build
  - cd build

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      case $COMPILER in
        gcc)
          cmake ../linux/epoll/  &&
          cmake --build .
          ;;
        clang)
          cmake -DCMAKE_TOOLCHAIN_FILE=../linux/clang.cmake ../linux/epoll/  &&
          cmake --build .
          ;;
      esac ;
    fi

