language: cpp

branches:
  except:
    - /^feature.*$/

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "QHBCY7S3ZYOtu5zujyMnyHg74srAIfFSKJbrlBdETk2T6YStPug3Z5PuY7ahXfPyM/4w7og8KyvuGZL0YsJrNaJSpsbDETtwvKEorzLjfKyRwDV2SyTpnSLauGgZmjPZnkXzp8lQIR+cIo7of6frjxd47E8WCKCGFJKa0pUG5Bw="
  matrix:
    - BUILD=gcc
    - BUILD=clang
    - BUILD=tests

before_install:
  - sudo pip install cpp-coveralls

install:
  - sudo apt-get install -qq cmake libboost-dev libboost-test-dev || /bin/true

before_script:
  - mkdir build
  - cd build

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      case ${BUILD} in
        gcc)
          cmake ../linux/epoll/  &&
          make
          ;;
        clang)
          cmake -DCMAKE_TOOLCHAIN_FILE=../linux/cmake/clang.cmake ../linux/epoll/  &&
          make
          ;;
        tests)
          cmake ../linux/epoll/tests/  &&
          make &&
          ctest -V &&
          coveralls --gcov-options '\-lp'
          ;;
      esac ;
    fi

addons:
  coverity_scan:
    project:
      name: "gatzka/cjet"
      description: "Build submitted via Travis CI"
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "cmake ../linux/epoll/"
    build_command: "make"
    branch_pattern: coverity_scan
